'use client'
import{useEffect,useState}from'react'
const labels:any={VIEW:'Открыла приглашение',NO_ATTEMPT:'Попытка нажать «Нет»',ANSWER:'Выбрала «Да»',PLACE_SELECT:'Выбрала место',DATETIME_SELECT:'Выбрала дату и время'}
const places:any={RESTAURANT:'Ресторан',CINEMA:'Кино',WALK:'Прогулка',HOME:'Дома'}
export default function Dashboard(){const[auth,setAuth]=useState<boolean|null>(null),[password,setPassword]=useState(''),[name,setName]=useState(''),[items,setItems]=useState<any[]>([]),[created,setCreated]=useState<any>(),[selected,setSelected]=useState<any>(),[events,setEvents]=useState<any[]>([]),[error,setError]=useState('')
async function refresh(){const r=await fetch('/api/invitations',{cache:'no-store'});if(r.status===401){setAuth(false);return}if(r.ok)setItems(await r.json())}
useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(x=>{setAuth(x.authenticated);if(x.authenticated)void refresh()})},[])
useEffect(()=>{if(!auth)return;const id=setInterval(()=>void refresh(),3000);return()=>clearInterval(id)},[auth])
useEffect(()=>{if(!auth||!selected)return;const es=new EventSource('/api/invitations/stream?token='+encodeURIComponent(selected.token));es.onmessage=()=>{void refresh();void inspect(selected)};return()=>es.close()},[auth,selected?.token])
async function login(){const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});if(r.ok){setAuth(true);setPassword('');void refresh()}else setError('Неверный пароль')}
async function create(){if(!name.trim())return;const r=await fetch('/api/invitations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipientName:name.trim()})});if(!r.ok){setError('Не удалось создать приглашение');return}setCreated(await r.json());setName('');void refresh()}
async function inspect(i:any){setSelected(i);const r=await fetch('/api/invitations/'+i.token+'/events');if(r.ok)setEvents(await r.json())}
if(auth===null)return <main className="shell"><section className="card"><p>Загрузка…</p></section></main>
if(!auth)return <main className="shell"><section className="card dashboard"><div className="eyebrow">Tima · private panel</div><h1 className="title">Вход</h1><div className="field"><label>Пароль</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void login()}/></div>{error&&<p className="error">{error}</p>}<button className="btn primary" onClick={()=>void login()}>Войти</button></section></main>
return <main className="shell"><section className="card dashboard"><div className="topline"><div><div className="eyebrow">Tima · private panel</div><h1 className="title">Приглашения</h1></div><button className="btn small" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setAuth(false)}}>Выйти</button></div><div className="field"><label>Имя получателя</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Имя" onKeyDown={e=>e.key==='Enter'&&void create()}/></div><button className="btn primary" onClick={()=>void create()}>Создать приглашение</button>{created?.url&&<div className="result"><div className="muted">Ссылка готова</div><div className="link">{created.url}</div><button className="btn small" onClick={()=>navigator.clipboard?.writeText(created.url)}>Копировать</button></div>}<div className="history"><h3>Все приглашения</h3>{items.map(i=><button className="invite-row" key={i.id} onClick={()=>void inspect(i)}><b>{i.recipientName}</b><span className="muted">{i.latestAnswer==='YES'?'Да':'Ожидает ответа'}{i.latestPlace?' · '+places[i.latestPlace]:''}{i.latestDate?' · '+i.latestDate+' '+(i.latestTime||''):''}</span></button>)}</div>{selected&&<div className="history"><h3>{selected.recipientName}</h3><div className="result"><div className="muted">Ссылка</div><div className="link">{typeof window!=='undefined'?location.origin:''}/invite/{selected.token}</div></div><h3>История действий</h3>{events.map(e=><div key={e.id}>{labels[e.type]||e.type}{e.place?' · '+places[e.place]:''}{e.responseDate?' · '+e.responseDate+' '+(e.responseTime||''):''}<br/><span className="muted">{new Date(e.createdAt).toLocaleString('ru-RU')}</span></div>)}</div>}</section></main>}
